schema_version: 1

context:
  version: "0.10.1"

package:
  name: conda-pypi
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/conda-pypi/conda_pypi-${{ version }}.tar.gz
  sha256: 179eac4ae82abe8441637df4e0b58aea6a09a56e02aaee9d167d4b2fd19793b3

build:
  # can't be noarch because we can't place EXTERNALLY-MANAGED in stdlib (first level is site-packages)
  # However, EXTERNALLY-MANAGED is temporarily disabled
  number: 2
  skip: match(python, "<3.10")
  script:
    - if: unix
      then: set -x
    - if: win
      then: "@ECHO ON"
    - ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - pip
    - hatchling >=1.26
    - hatch-vcs >=0.2.0
  run:
    - python
    - conda >=26.1.0
    - pip >=23.0.1
    - packaging
    - unearth
    - python-build
    - python-installer >=1.0
    - platformdirs
    - conda-index >=0.11.0
    - conda-package-streaming >=0.11

tests:
  - python:
      imports:
        - conda_pypi
        - conda_pypi.main
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      # Using 'conda pypi' directly on Windows fails due to the actual 'base' conda being found earlier than test-env's conda
      - python -m conda pypi --help

about:
  license: MIT
  license_file: LICENSE
  summary: Better PyPI interoperability for the conda ecosystem
  homepage: https://github.com/conda/conda-pypi
  repository: https://github.com/conda/conda-pypi
  documentation: https://conda.github.io/conda-pypi

extra:
  recipe-maintainers:
    - danyeaw
    - ryanskeith
    - jaimergp
    - jezdez
